### ISSUE TITLE
bug: insert 抜けずにmanual補完すると重くなる

### ISSUE THREAD

**Issue by LumaKernel** [LumaKernel/ddc-coc-patched#3]
以下は補完が表示された瞬間に `<c-w>(manual補完するコマンド)` を繰り返している

![osokunaru](https://user-images.githubusercontent.com/29811106/135879621-74257ea0-f13c-40aa-8d15-5e213e98016b.gif)

file source では発生しなかったのでこちらに問題ありそう

**Comment by Shougo** [comment]
coc.nvimへのリクエストが多重に飛んでるのだと思います。
状態をチェックしてキャンセルする仕組みが必要かと
